capture_prefix = "particle_"
seed = 123
window_width = 800
window_height = 800
# selected_emitters = ["noise_field_green", "noise_field_blue", "noise_field_purple"]
selected_emitters = ["rainbow"]

[color_pickers]
[color_pickers.mono_green]
hue = 129
saturation = 0.3
range_lightness = [0.11, 0.23]
num_colors = 5

[color_pickers.mono_blue]
hue = 227
saturation = 0.7
range_lightness = [0.0, 0.3]
num_colors = 5

[color_pickers.mono_purple]
hue = 276
saturation = 0.7
range_lightness = [0.0, 0.3]
num_colors = 5

[color_pickers.rainbow]
range_hue = [0, 360]
saturation = 0.8
lightness = 0.6
num_colors = 10

[emitters]
[emitters.rainbow]
position = [10.1, -10.1]
velocity = [0, 0]
life_span = 60
noise_field = true
noise_scale = 0.005
noise_strength = 0.5
flight_size = 10
randomize_position = false
radius = 4
stroke_weight = 0
color_picker = "rainbow"
mover = "lisajous_0"
# visualize_noise_field = true


[emitters.noise_field_green]
position = [10.1, -10.1]
velocity = [0, 0]
life_span = 100
noise_field = true
noise_scale = 0.005
noise_strength = 0.5
flight_size = 100
randomize_position = false
radius = 4
stroke_weight = 0
color_picker = "mono_green"
# color_picker = "rainbow"
mover = "lisajous_1"
# visualize_noise_field = true

[emitters.noise_field_blue]
position = [-200.1, -7.1]
velocity = [0, 0]
life_span = 100
noise_field = true
noise_scale = 0.005
noise_strength = 0.5
flight_size = 100
randomize_position = false
radius = 4
stroke_weight = 0
color_picker = "mono_blue"
# color_picker = "rainbow"
mover = "lisajous_2"

[emitters.noise_field_purple]
position = [150.1, 150.1]
velocity = [0, 0]
life_span = 100
noise_field = true
noise_scale = 0.005
noise_strength = 0.5
flight_size = 100
randomize_position = false
radius = 4
stroke_weight = 0
color_picker = "mono_purple"
# color_picker = "rainbow"
mover = "lisajous_3"

[movers]
[movers.lisajous_0]
mover_type = "p_elipse"
inner = [1, 3]
outer = [1, 1]
scale = [800, 800]
translation = [0, 0]
rotation_angle = 0
rotation_speed = 2.1

[movers.lisajous_1]
mover_type = "p_elipse"
inner = [1, 3]
outer = [1, 1]
scale = [800, 800]
translation = [0, 0]
rotation_angle = 0
rotation_speed = 0

[movers.lisajous_2]
mover_type = "p_elipse"
inner = [1, 3]
outer = [1, 1]
scale = [800, 800]
# translation = [-100, 0]
rotation_angle = 2.0943951024 # 120 degrees
rotation_speed = 0

[movers.lisajous_3]
mover_type = "p_elipse"
inner = [1, 3]
outer = [1, 1]
scale = [800, 800]
# translation = [100, 0]
rotation_angle =  4.1887902048 # 240 degrees
rotation_speed = 0

