capture_prefix = "particle_"
seed = 42
window_width = 800
window_height = 800
use_emitters = ["emitter_1"]

[color_pickers]
[color_pickers.mono_green]
hue = 129
saturation = 0.5
range_lightness = [0.11, 0.23]
num_colors = 5

[color_pickers.mono_blue]
hue = 227
saturation = 0.7
range_lightness = [0.0, 0.3]
num_colors = 5

[color_pickers.mono_purple]
hue = 276
saturation = 0.7
range_lightness = [0.0, 0.3]
num_colors = 5

[color_pickers.rainbow]
range_hue = [0, 360]
saturation = 0.5
lightness = 0.5
num_colors = 10

[emitters]
[emitters.emitter_1]
position = [0, 0]
initial_velocity = [2, 2]
life_span = 512
flight_size = 1
randomize_position = false
randomize_velocity = true
radius = 10
stroke_weight = 2
color_picker = "rainbow"

[emitters.noise_field_green]
position = [10.1, -10.1]
velocity = [0, 0]
life_span = 600
noise_field = true
noise_scale = 0.005
noise_strength = 0.01
flight_size = 10
randomize_position = false
radius = 4
stroke_weight = 0
color_picker = "mono_green"
visualize_noise_field = true

[emitters.noise_field_blue]
position = [-200.1, -7.1]
velocity = [0, 0]
life_span = 600
noise_field = true
noise_scale = 0.006
noise_strength = 0.05
flight_size = 10
randomize_position = false
radius = 4
stroke_weight = 0
color_picker = "mono_blue"

[emitters.noise_field_purple]
position = [150.1, 150.1]
velocity = [0, 0]
life_span = 600
noise_field = true
noise_scale = 0.005
noise_strength = 0.03
flight_size = 10
randomize_position = false
radius = 4
stroke_weight = 0
color_picker = "mono_purple"
